### PR TITLE
fix(core): Menu being rerendered on invalid applet requests

### PR DESCRIPTION
**Pull request by amanCypherock**

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6187 On device the main menu can't be scrolled because of cysync background request command](https://app.clickup.com/t/9002019994/PRF-6187)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6187 On device the main menu can't be scrolled because of cysync background request command](https://app.clickup.com/t/9002019994/PRF-6187)

**Comment by rohanagarwal94** [comment]
Task linked: [PRF-6187 On device the main menu can't be scrolled because of cysync background request command](https://app.clickup.com/t/9002019994/PRF-6187)

**Review by ujjwal-cyph — APPROVED** [review]
LGTM

**Pull request merged**
