### PR TITLE
options released on unused button presses

### PR DESCRIPTION
**Pull request by amanCypherock**
Fixes https://app.clickup.com/t/37308523/CHI-1943

### CODE REVIEW

**Comment by amanCypherock** [comment]
Need to copy this change in all UI handlers so highlight screen issues are not reported

**Comment by amanCypherock** [comment]
We need to copy this change in all UI handlers

**Comment by vbcypherock** [comment]
Task linked: [CHI-1943 Release option in menu screen on unused joystick moves](https://app.clickup.com/t/37308523/CHI-1943)

**Comment by amanCypherock** [comment]
Change merged with https://github.com/Cypherock/x1_wallet_firmware/pull/166/files

**Pull request closed without merging**
