### PR TITLE
Fix/wallet creation/chi 2138

### PR DESCRIPTION
**Pull request by amanCypherock**
Fixes added

https://app.clickup.com/t/37308523/CHI-2141 (only macro is set here)
https://app.clickup.com/t/37308523/CHI-2148
https://app.clickup.com/t/37308523/CHI-2157
https://app.clickup.com/t/37308523/CHI-2140
https://app.clickup.com/t/37308523/PRD-1817

### CODE REVIEW

**Comment by vbcypherock** [comment]
Task linked: [CHI-2138 Firmware Review Points - Dec-2022](https://app.clickup.com/t/37308523/CHI-2138)

**Comment by vbcypherock** [comment]
Task linked: [CHI-2157 Remove malloc for temporary variables and Use SHA256_DIGEST_LENGTH instead of sizeof(temp)](https://app.clickup.com/t/37308523/CHI-2157)

**Comment by vbcypherock** [comment]
Task linked: [CHI-2141 Move security relevant and variables declared with CONFIDENTIAL macro to SRAM2](https://app.clickup.com/t/37308523/CHI-2141)

**Comment by vbcypherock** [comment]
Task linked: [CHI-2148 Pass secret_size as no_of_bytes to support arbitrary data in verify_shares_NC2](https://app.clickup.com/t/37308523/CHI-2148)

**Review by ujjwal-cyph — CHANGES_REQUESTED** [review]
correct the malloc behaviour in `src\level_four\core\controller\send_transaction_controller.c`. its allocating multiple times but frees only once

**Review by ujjwal-cyph — APPROVED** [review]

**Pull request merged**
